<a href="https://colab.research.google.com/github/ShaliniSakthivel-DA/Python-Learning-CaseStudies/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Installing Pandas

!pip install pandas

Collecting panda
  Downloading panda-0.3.1.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from panda) (75.2.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from panda) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->panda) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->panda) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->panda) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->panda) (2026.5.20)
Building wheels for collected packages: panda
  Building wheel for panda (setup.py) ... done
  Created wheel for panda: filename=panda-0.3.1-py3-none-any.whl size=7239 sha256=ce658806c88d68fcea72dca231aad5e8991e0aa0a154b2978e581ccf42f2498e
  Stored in directory: /root/.cache/pip/wheels/98/41/5b/6ca54e0b6a35e1b7248c12f56fcb753dfb7717fefaa0fb45f5
Successfully built panda
Installing collected packages: panda
Successfully installed panda-0.3.1

In [2]:
#Importing pandas
import pandas as pd

In [3]:
# Series 1D labeled array

s = pd.Series([10,20,20,40])
print(s)
print(type(s))

0    10
1    20
2    20
3    40
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
# DataFrame: Create from a dictionary: 2D labeled table

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Age': [24, 30, 28, 35, 22, 40],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Berlin', 'Sydney']
}
print(data)

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'], 'Age': [24, 30, 28, 35, 22, 40], 'City': ['New York', 'London', 'Paris', 'Tokyo', 'Berlin', 'Sydney']}

In [7]:
df = pd.DataFrame(data)
df

      Name  Age      City
0    Alice   24  New York
1      Bob   30    London
2  Charlie   28     Paris
3    David   35     Tokyo
4      Eva   22    Berlin
5    Frank   40    Sydney

In [5]:
import pandas as pd

students = ["Shalini", "Arun", "Priya", "Karthik", "Divya"]

df = pd.DataFrame(students, columns=["Student_Name"])

print(df)

  Student_Name
0      Shalini
1         Arun
2        Priya
3      Karthik
4        Divya

In [9]:
df = pd.DataFrame(students)
df

         0
0  Shalini
1     Arun
2    Priya
3  Karthik
4    Divya

In [48]:
# Creating Dictionary
data = {
    'ID': [101, 102, 103, 104, 105, 106],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Age': [24, 30, 28, 35, 22, 40],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Berlin', 'Sydney'],
    'Salary': [50000, 60000, 55000, 70000, 48000, 75000],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing', 'Finance']
}

df = pd.DataFrame(data)
df

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
4  105      Eva   22    Berlin   48000  Marketing
5  106    Frank   40    Sydney   75000    Finance

In [12]:
#Accessing Columns in Pandas DataFrame

df["Name"]  # Single Element

df[['ID','Name']] # Multiple Elements

    ID     Name
0  101    Alice
1  102      Bob
2  103  Charlie
3  104    David
4  105      Eva
5  106    Frank

In [15]:
#Accessing Rows in Pandas DataFrame

df[0:3]
df[2:5]

    ID     Name  Age    City  Salary Department
2  103  Charlie   28   Paris   55000    Finance
3  104    David   35   Tokyo   70000         IT
4  105      Eva   22  Berlin   48000  Marketing

In [31]:
# loc[]  -> Label Based Indexing
# Syntax: df.loc[row_label, column_name]

print("\n---------Single loc------------")

print(df.loc[2,'Name'])
print(df.loc[4,'Department']) # indexing
print(df.loc[3:3])
print(df.loc[0:3]) # Single Row Single coulmn
print("\n---------Multiple loc------------")
print(df.loc[2:3,['Name','Age','City']]) #Multiple Column # slicing

---------Single loc------------
Charlie
Marketing
    ID   Name  Age   City  Salary Department
3  104  David   35  Tokyo   70000         IT
    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT

---------Multiple loc------------
      Name  Age   City
2  Charlie   28  Paris
3    David   35  Tokyo

In [40]:
# iloc[] -> Integer Position Based Indexing
# Syntax: df.iloc[row_index, column_index]


print(df.iloc[3])

df.iloc[0,3] # ',' give location based on integer(Row, Column)

print(df.iloc[0:3])

ID              104
Name          David
Age              35
City          Tokyo
Salary        70000
Department       IT
Name: 3, dtype: object
    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance

In [41]:
print(df.loc[0:2]) # loc include end lable
print(df.iloc[0:2]) # loc excludes end lable like slicin

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
    ID   Name  Age      City  Salary Department
0  101  Alice   24  New York   50000         HR
1  102    Bob   30    London   60000         IT

In [42]:
print(df.loc[0,'Name'])
print(df.iloc[0,1])

Alice
Alice

In [46]:
# Filtering Data

df['Age'] <= 30

df_age_sal = df[(df['Age'] <=30) & (df['Salary'] <=50000) ]
df_age_sal

    ID   Name  Age      City  Salary Department
0  101  Alice   30  New York   50000         HR
4  105    Eva   30    Berlin   48000  Marketing

In [49]:
# Sorting Data
df.sort_values("Age")

    ID     Name  Age      City  Salary Department
4  105      Eva   22    Berlin   48000  Marketing
0  101    Alice   24  New York   50000         HR
2  103  Charlie   28     Paris   55000    Finance
1  102      Bob   30    London   60000         IT
3  104    David   35     Tokyo   70000         IT
5  106    Frank   40    Sydney   75000    Finance

In [50]:
# Adding Column
df.loc[6] =[107,'George',35,'Paris',55000,"IT"]
df

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
4  105      Eva   22    Berlin   48000  Marketing
5  106    Frank   40    Sydney   75000    Finance
6  107   George   35     Paris   55000         IT

In [51]:
df.loc[len(df)] =[108,'John',25,'Paris',59000,"IT"]
df

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
4  105      Eva   22    Berlin   48000  Marketing
5  106    Frank   40    Sydney   75000    Finance
6  107   George   35     Paris   55000         IT
7  108     John   25     Paris   59000         IT

In [54]:
# Updating Values
df.loc[0,'Salary'] = 40000

df.loc[df['Name']== 'Frank',"Age"] =20
df

df.loc[df['Name']== 'John','Department'] = "HR"
df

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   40000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
4  105      Eva   22    Berlin   48000  Marketing
5  106    Frank   20    Sydney   75000    Finance
6  107   George   35     Paris   55000         IT
7  108     John   25     Paris   59000         HR